### ISSUE TITLE
Docker instructions just exit without effect

### ISSUE THREAD

**Issue by adrianmay** [oyzzo/camodet#6]
As title really. I substituted the url to my ip cam in your example docker run command, it downloaded all the images, and did nothing else.

**Comment by oyzzo** [comment]
Hi @adrianmay, 

The camodet project has been unmaintained for a long time, it could be some versions issue. 

There is a new python rewrite of the tool that you can use easily:
https://github.com/jim17/camodet_python/releases
https://github.com/jim17/camodet_python

Hope it helps! 
I'll update the README and point to the new python version.

**Comment by adrianmay** [comment]
Thanks Noel. Just checking it out.
I just bounced off zoneminder cos I couldn't build/configure my own code
changes, and this looks like a good place to start.
My goal is to have a motion detection alg that computes differences of
pixel colours from their long term typical values, then tracks the centre
of gravity of the set of active pixels. If I can distinguish changes
towards vs away from the long term norm, then I can pick out both the
leading and the trailing edge of a moving object. Things approaching the
camera directly also need detecting. By "typical" I don't just mean
average. I'd like to cater for e.g. green leaves waving against a blue sky
and specifically recognise the two colours and mixtures of them (I'll whack
the resolution down at the outset).
Does that sound like fun?
Adrian.

**Comment by oyzzo** [comment]
Hi @adrianmay,
It sounds great! It's easy to use this code or the python version as a start point and add your changes.
Using OpenCV is really easy to implement your described algorithm.

I implemented this code because zoneminder (and the other alternatives) was too complicate to install and setup, having a simple tool that does exacly what you need is great.

Using the C++ version requires to prepare the dependencies either by compiling them or install them which can be a time consuming task depending on the development platform.
Using the python version is as easy as "pip install" the needed libraries in any platform :)

Good luck with your project!

**Comment by adrianmay** [comment]
Thanks. I'll keep it on GitHub so you can pull the alg if you like it.

**Comment by adrianmay** [comment]
Hi Noel,

I'm getting a strange effect where the frames in the video come out in the
wrong order. The go 1 2 5 3 4 6 etc. In the input view window they look
fine. I can see this cos my ip cctv only seems to manage 1 fps. Did you
ever notice that?

I was also gobsmacked that the waitKey seems necessary to make the input
view window show any frames.

Was the C version this temperamental?

Adrian.
